; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


; Versão Arduino do ESP32-C3 Super Mini no PlatformIO
[env:esp32c3-supermini]
platform        = espressif32
board           = esp32-c3-devkitm-1
framework       = arduino
monitor_speed   = 115200
upload_speed    = 921600



; upload_protocol = espota
; Se você configurou mDNS no código (ArduinoOTA.setHostname("esp32-ota")),
; então pode usar "esp32-ota.local". Caso contrário, coloque o IP que o ESP recebeu.
; upload_port     = 192.168.4.217

; Flags adicionais para o espota:
; upload_flags = 
;     --port=3232
;     --auth=robotica2025


; Partições personalizadas para usar melhor a memória da Flash
; board_build.partitions = partitions.csv
board_build.flash_size = 4MB


; Bibliotecas necessárias para o projeto
lib_deps = 
	olikraus/U8g2 @ ^2.35.15

; build_flags opcionais (ative apenas um modo principal por vez):
build_flags =
;   -DMOTOR_SELF_TEST       ; executa motor_selftest.cpp (sem WiFi/ESP-NOW)
;   -DGY521_SELF_TEST       ; executa gy521_selftest.cpp (teste do GY-521)
	-DUSE_ESPNOW_CONTROL    ; executa espnow_control.cpp (controle por ESP-NOW)
;   -DSTEPPER_DIRECT_FREQ_MODE
;   -DDEBUG_MOTOR_VERBOSE